apiVersion: v1
kind: ConfigMap
metadata:
  name: tolkflip-config
  namespace: tolkflip
data:
  CASSANDRA_HOSTS: "cassandra-service"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  MINIO_ENDPOINT: "minio-service"
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  ALLOWED_ORIGINS: "*"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  USER_SERVICE_URL: "http://user-service:3002"
  CHAT_SERVICE_URL: "http://chat-service:3003"
  TRANSLATION_SERVICE_URL: "http://translation-service:3004"
  TRANSCRIPTION_SERVICE_URL: "http://transcription-service:3005"
  MEDIA_SERVICE_URL: "http://media-service:3006"
  PRESENCE_SERVICE_URL: "http://presence-service:3007"
